name: gces_social
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  pin_code_fields: 7.3.0
  dio: 4.0.0
  percent_indicator: 3.4.0
  url_launcher: 6.0.12
  retrofit: 2.0.1
  shared_preferences: 2.0.8
  pretty_dio_logger: any
  flutter_spinkit: 5.1.0
  lottie: 1.2.1
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  retrofit_generator: any
  build_runner: any
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:
  image: assets/images/logo.png
  color: "49adc4"


flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  fonts: 
    - family: Mulish
      fonts: 
        - asset: assets/fonts/Mulish-VariableFont_wght.ttf
  uses-material-design: true

